In [3]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [6]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [7]:
tf.test.is_built_with_cuda()

True

In [12]:
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.cifar10.load_data()

In [13]:
x_train.shape

(50000, 32, 32, 3)

In [15]:
x_train[0]

array([[[ 59,  62,  63],
        [ 43,  46,  45],
        [ 50,  48,  43],
        ...,
        [158, 132, 108],
        [152, 125, 102],
        [148, 124, 103]],

       [[ 16,  20,  20],
        [  0,   0,   0],
        [ 18,   8,   0],
        ...,
        [123,  88,  55],
        [119,  83,  50],
        [122,  87,  57]],

       [[ 25,  24,  21],
        [ 16,   7,   0],
        [ 49,  27,   8],
        ...,
        [118,  84,  50],
        [120,  84,  50],
        [109,  73,  42]],

       ...,

       [[208, 170,  96],
        [201, 153,  34],
        [198, 161,  26],
        ...,
        [160, 133,  70],
        [ 56,  31,   7],
        [ 53,  34,  20]],

       [[180, 139,  96],
        [173, 123,  42],
        [186, 144,  30],
        ...,
        [184, 148,  94],
        [ 97,  62,  34],
        [ 83,  53,  34]],

       [[177, 144, 116],
        [168, 129,  94],
        [179, 142,  87],
        ...,
        [216, 184, 140],
        [151, 118,  84],
        [123,  92,  72]]

In [20]:
x_train_scaled=x_train/255


In [21]:
x_train_scaled

array([[[[0.23137255, 0.24313725, 0.24705882],
         [0.16862745, 0.18039216, 0.17647059],
         [0.19607843, 0.18823529, 0.16862745],
         ...,
         [0.61960784, 0.51764706, 0.42352941],
         [0.59607843, 0.49019608, 0.4       ],
         [0.58039216, 0.48627451, 0.40392157]],

        [[0.0627451 , 0.07843137, 0.07843137],
         [0.        , 0.        , 0.        ],
         [0.07058824, 0.03137255, 0.        ],
         ...,
         [0.48235294, 0.34509804, 0.21568627],
         [0.46666667, 0.3254902 , 0.19607843],
         [0.47843137, 0.34117647, 0.22352941]],

        [[0.09803922, 0.09411765, 0.08235294],
         [0.0627451 , 0.02745098, 0.        ],
         [0.19215686, 0.10588235, 0.03137255],
         ...,
         [0.4627451 , 0.32941176, 0.19607843],
         [0.47058824, 0.32941176, 0.19607843],
         [0.42745098, 0.28627451, 0.16470588]],

        ...,

        [[0.81568627, 0.66666667, 0.37647059],
         [0.78823529, 0.6       , 0.13333333]

In [22]:

x_test_scaled=x_test/255

In [24]:
y_train_categorical=keras.utils.to_categorical(
    y_train,num_classes=10,dtype='float32'

    )
y_train_categorical

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [25]:

y_test_categorical=keras.utils.to_categorical(
    y_test,num_classes=10,dtype='float32'
)

In [32]:
model=keras.Sequential([
    keras.layers.Flatten(input_shape=(32,32,3)),
    keras.layers.Dense(3000,activation='relu'),
    keras.layers.Dense(1000,activation='relu'),
    keras.layers.Dense(10,activation='sigmoid')
])
model.compile(optimizer='SGD',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(x_train_scaled,y_train_categorical,epochs=50)

Epoch 1/50
1563/1563 [==============================] - 97s 62ms/step - loss: 1.8129 - accuracy: 0.3541
Epoch 2/50
1563/1563 [==============================] - 96s 62ms/step - loss: 1.6231 - accuracy: 0.4283
Epoch 3/50
1563/1563 [==============================] - 96s 62ms/step - loss: 1.5424 - accuracy: 0.4548
Epoch 4/50
1563/1563 [==============================] - 97s 62ms/step - loss: 1.4819 - accuracy: 0.4764
Epoch 5/50
1563/1563 [==============================] - 96s 62ms/step - loss: 1.4325 - accuracy: 0.4930
Epoch 6/50
1563/1563 [==============================] - 96s 62ms/step - loss: 1.3875 - accuracy: 0.5111
Epoch 7/50
1563/1563 [==============================] - 96s 61ms/step - loss: 1.3508 - accuracy: 0.5251
Epoch 8/50
1563/1563 [==============================] - 96s 61ms/step - loss: 1.3163 - accuracy: 0.5388
Epoch 9/50
1563/1563 [==============================] - 96s 61ms/step - loss: 1.2816 - accuracy: 0.5509
Epoch 10/50
1563/1563 [==============================] - 96s 61m